//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICompontsReturn")]
    public interface ICompontsReturn {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompontsReturn/ReturnArmor", ReplyAction="http://tempuri.org/ICompontsReturn/ReturnArmorResponse")]
        System.Collections.Generic.List<ClassLibrary.DataModel.Armor> ReturnArmor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompontsReturn/ReturnArmor", ReplyAction="http://tempuri.org/ICompontsReturn/ReturnArmorResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ClassLibrary.DataModel.Armor>> ReturnArmorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompontsReturn/ReturnWeapon", ReplyAction="http://tempuri.org/ICompontsReturn/ReturnWeaponResponse")]
        System.Collections.Generic.List<ClassLibrary.DataModel.Weapon> ReturnWeapon();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompontsReturn/ReturnWeapon", ReplyAction="http://tempuri.org/ICompontsReturn/ReturnWeaponResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ClassLibrary.DataModel.Weapon>> ReturnWeaponAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompontsReturn/ReturnEnemyShip", ReplyAction="http://tempuri.org/ICompontsReturn/ReturnEnemyShipResponse")]
        System.Collections.Generic.List<ClassLibrary.DataModel.EnemyShip> ReturnEnemyShip();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompontsReturn/ReturnEnemyShip", ReplyAction="http://tempuri.org/ICompontsReturn/ReturnEnemyShipResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ClassLibrary.DataModel.EnemyShip>> ReturnEnemyShipAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompontsReturn/ReturnStarShip", ReplyAction="http://tempuri.org/ICompontsReturn/ReturnStarShipResponse")]
        System.Collections.Generic.List<ClassLibrary.DataModel.StarShip> ReturnStarShip();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompontsReturn/ReturnStarShip", ReplyAction="http://tempuri.org/ICompontsReturn/ReturnStarShipResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ClassLibrary.DataModel.StarShip>> ReturnStarShipAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompontsReturn/Is_successful_registration", ReplyAction="http://tempuri.org/ICompontsReturn/Is_successful_registrationResponse")]
        bool Is_successful_registration(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompontsReturn/Is_successful_registration", ReplyAction="http://tempuri.org/ICompontsReturn/Is_successful_registrationResponse")]
        System.Threading.Tasks.Task<bool> Is_successful_registrationAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompontsReturn/ReturnUser", ReplyAction="http://tempuri.org/ICompontsReturn/ReturnUserResponse")]
        ClassLibrary.DataModel.User ReturnUser(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompontsReturn/ReturnUser", ReplyAction="http://tempuri.org/ICompontsReturn/ReturnUserResponse")]
        System.Threading.Tasks.Task<ClassLibrary.DataModel.User> ReturnUserAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompontsReturn/UserRegestration", ReplyAction="http://tempuri.org/ICompontsReturn/UserRegestrationResponse")]
        bool UserRegestration(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompontsReturn/UserRegestration", ReplyAction="http://tempuri.org/ICompontsReturn/UserRegestrationResponse")]
        System.Threading.Tasks.Task<bool> UserRegestrationAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompontsReturn/ReturnAllUser", ReplyAction="http://tempuri.org/ICompontsReturn/ReturnAllUserResponse")]
        System.Collections.Generic.List<ClassLibrary.DataModel.User> ReturnAllUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompontsReturn/ReturnAllUser", ReplyAction="http://tempuri.org/ICompontsReturn/ReturnAllUserResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ClassLibrary.DataModel.User>> ReturnAllUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompontsReturn/Save", ReplyAction="http://tempuri.org/ICompontsReturn/SaveResponse")]
        bool Save(ClassLibrary.DataModel.User user, ClassLibrary.DataModel.StarShip starShip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompontsReturn/Save", ReplyAction="http://tempuri.org/ICompontsReturn/SaveResponse")]
        System.Threading.Tasks.Task<bool> SaveAsync(ClassLibrary.DataModel.User user, ClassLibrary.DataModel.StarShip starShip);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICompontsReturnChannel : GUI.ServiceReference1.ICompontsReturn, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompontsReturnClient : System.ServiceModel.ClientBase<GUI.ServiceReference1.ICompontsReturn>, GUI.ServiceReference1.ICompontsReturn {
        
        public CompontsReturnClient() {
        }
        
        public CompontsReturnClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompontsReturnClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompontsReturnClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompontsReturnClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<ClassLibrary.DataModel.Armor> ReturnArmor() {
            return base.Channel.ReturnArmor();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ClassLibrary.DataModel.Armor>> ReturnArmorAsync() {
            return base.Channel.ReturnArmorAsync();
        }
        
        public System.Collections.Generic.List<ClassLibrary.DataModel.Weapon> ReturnWeapon() {
            return base.Channel.ReturnWeapon();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ClassLibrary.DataModel.Weapon>> ReturnWeaponAsync() {
            return base.Channel.ReturnWeaponAsync();
        }
        
        public System.Collections.Generic.List<ClassLibrary.DataModel.EnemyShip> ReturnEnemyShip() {
            return base.Channel.ReturnEnemyShip();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ClassLibrary.DataModel.EnemyShip>> ReturnEnemyShipAsync() {
            return base.Channel.ReturnEnemyShipAsync();
        }
        
        public System.Collections.Generic.List<ClassLibrary.DataModel.StarShip> ReturnStarShip() {
            return base.Channel.ReturnStarShip();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ClassLibrary.DataModel.StarShip>> ReturnStarShipAsync() {
            return base.Channel.ReturnStarShipAsync();
        }
        
        public bool Is_successful_registration(string login, string password) {
            return base.Channel.Is_successful_registration(login, password);
        }
        
        public System.Threading.Tasks.Task<bool> Is_successful_registrationAsync(string login, string password) {
            return base.Channel.Is_successful_registrationAsync(login, password);
        }
        
        public ClassLibrary.DataModel.User ReturnUser(string login, string password) {
            return base.Channel.ReturnUser(login, password);
        }
        
        public System.Threading.Tasks.Task<ClassLibrary.DataModel.User> ReturnUserAsync(string login, string password) {
            return base.Channel.ReturnUserAsync(login, password);
        }
        
        public bool UserRegestration(string login, string password) {
            return base.Channel.UserRegestration(login, password);
        }
        
        public System.Threading.Tasks.Task<bool> UserRegestrationAsync(string login, string password) {
            return base.Channel.UserRegestrationAsync(login, password);
        }
        
        public System.Collections.Generic.List<ClassLibrary.DataModel.User> ReturnAllUser() {
            return base.Channel.ReturnAllUser();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ClassLibrary.DataModel.User>> ReturnAllUserAsync() {
            return base.Channel.ReturnAllUserAsync();
        }
        
        public bool Save(ClassLibrary.DataModel.User user, ClassLibrary.DataModel.StarShip starShip) {
            return base.Channel.Save(user, starShip);
        }
        
        public System.Threading.Tasks.Task<bool> SaveAsync(ClassLibrary.DataModel.User user, ClassLibrary.DataModel.StarShip starShip) {
            return base.Channel.SaveAsync(user, starShip);
        }
    }
}
